server:
  # Use '0.0.0.0' (ipv4) or '::' (ipv6) if connecting from other hosts
  address: '0.0.0.0'
  port: 40772
  workers: 10

channels:
  - name: MX
    type: GR
    channel: '20'
  - name: CX
    type: GR
    channel: '21'
  - name: TBS
    type: GR
    channel: '22'
  - name: TX
    type: GR
    channel: '23'
  - name: EX
    type: GR
    channel: '24'
  - name: NTV
    type: GR
    channel: '25'
  - name: NHK E
    type: GR
    channel: '26'
  - name: NHK G
    type: GR
    channel: '27'
  - name: BS1
    type: BS
    channel: BS15_0
    excluded-services: [700, 701, 707, 929]
  - name: BSプレミアム
    type: BS
    channel: BS03_1
    services: [103, 104]
  - name: BS日テレ
    type: BS
    channel: BS13_0
  - name: BS朝日
    type: BS
    channel: BS01_0
  - name: BS-TBS
    type: BS
    channel: BS01_1
  - name: BSテレ東
    type: BS
    channel: BS01_2
    excluded-services: [777]
  - name: BSフジ
    type: BS
    channel: BS13_1
  - name: BS11
    type: BS
    channel: BS09_0
  - name: BS12
    type: BS
    channel: BS09_2
  - name: 放送大学
    type: BS
    channel: BS11_2
    excluded-services: [531]

tuners:
  - name: bs1
    types: [BS]
    command: >-
      recpt1 --device /dev/px4video0 {{channel}} {{duration}} -
  # Use a tuner on a remote host connected with SSH.
  # You need to mount a SSH private key onto a Docker container.
  - name: remote-dvb
    types: [GR]
    command: >-
      ssh HOST recdvb {{channel}} {{duration}} -
  # Use a Mirakurun-compatible server as a tuner.
  # The duration query parameter works only for mirakc servers.
  - name: upstream
    types: [GR, BS]
    command: >-
      curl -sG http://HOST:40772/api/channels/{{channel_type}}/{{channel}}/stream
      -d duration={{duration}}

tools:
  scan-services: >-
    mirakc-arib scan-services{{#xsids}} --xsid={{.}}{{/xsids}}
  sync-clock: >-
    mirakc-arib sync-clock
  collect-eits: >-
    mirakc-arib collect-eits{{#xsids}} --xsid={{.}}{{/xsids}}
  filter-service: >-
    mirakc-arib filter-service --sid={{sid}}
  filter-program: >-
    mirakc-arib filter-program --sid={{sid}} --eid={{eid}}
    --clock-pcr={{clock_pcr}} --clock-time={{clock_time}}
    --start-margin=5000 --end-margin=5000
  # Preprocess TS packets by using a server running on a remote host.
  # The preprocess command is called before the filter-program command.
  preprocess: >-
    socat - tcp-connect:HOST:40773
  # Postprocess TS packets by using a server running on a remote host.
  # The postprocess command is called after the filter-program command.
  postprocess: >-
    socat - tcp-connect:HOST:40774

epg-cache-dir: /var/lib/mirakc/epg
