server:
  address: '0.0.0.0'
  port: 40772
  workers: 10

channels:
  - name: MX
    type: GR
    channel: '20'
  - name: CX
    type: GR
    channel: '21'
  - name: TBS
    type: GR
    channel: '22'
  - name: TX
    type: GR
    channel: '23'
  - name: EX
    type: GR
    channel: '24'
  - name: NTV
    type: GR
    channel: '25'
  - name: NHK E
    type: GR
    channel: '26'
  - name: NHK G
    type: GR
    channel: '27'
  - name: BS1
    type: BS
    channel: BS15_0
    excluded-services: [700, 701, 707, 929]
  - name: BSプレミアム
    type: BS
    channel: BS03_1
    services: [103, 104]
  - name: BS日テレ
    type: BS
    channel: BS13_0
  - name: BS朝日
    type: BS
    channel: BS01_0
  - name: BS-TBS
    type: BS
    channel: BS01_1
  - name: BSテレ東
    type: BS
    channel: BS01_2
    excluded-services: [777]
  - name: BSフジ
    type: BS
    channel: BS13_1
  - name: BS11
    type: BS
    channel: BS09_0
  - name: BS12
    type: BS
    channel: BS09_2
  - name: 放送大学
    type: BS
    channel: BS11_2
    excluded-services: [531]

tuners:
  - name: gr1
    types: [GR]
    command: >-
      recpt1 --device /dev/px4video2 {{channel}} {{duration}} -
  - name: gr2
    types: [GR]
    command: >-
      recpt1 --device /dev/px4video3 {{channel}} {{duration}} -
  - name: gr3
    types: [GR]
    command: >-
      recpt1 --device /dev/px4video6 {{channel}} {{duration}} -
  - name: gr4
    types: [GR]
    command: >-
      recpt1 --device /dev/px4video7 {{channel}} {{duration}} -
  - name: bs1
    types: [BS]
    command: >-
      recpt1 --device /dev/px4video0 {{channel}} {{duration}} -
  - name: bs2
    types: [BS]
    command: >-
      recpt1 --device /dev/px4video1 {{channel}} {{duration}} -
  - name: bs3
    types: [BS]
    command: >-
      recpt1 --device /dev/px4video4 {{channel}} {{duration}} -
  - name: bs4
    types: [BS]
    command: >-
      recpt1 --device /dev/px4video5 {{channel}} {{duration}} -

tools:
  scan-services: >-
    mirakc-arib scan-services{{#xsids}} --xsid={{.}}{{/xsids}}
  collect-eits: >-
    mirakc-arib collect-eits{{#xsids}} --xsid={{.}}{{/xsids}}
  filter-service: >-
    mirakc-arib filter-packets --sid={{sid}}
  filter-program: >-
    mirakc-arib filter-packets --sid={{sid}} --eid={{eid}}

epg-cache-dir: /var/lib/mirakc/epg
