name: Docker

on:
  - push
  - repository_dispatch

jobs:
  build-images:
    strategy:
      matrix:
        arch:
          - amd64
          - arm32v5
          - arm32v7
          - arm64v8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup QEMU user-mode emulation
        run: |-
          sudo apt-get update
          sudo apt-get install -y qemu qemu-user-static
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - name: Build image
        env:
          DOCKER_BUILDKIT: 1
        # Experimental features including the --squash option has not been
        # supported in GitHub Actions at this moment...
        run: ./build --prefix masnagam --no-cache ${{ matrix.arch }}
      - name: Login to DockerHub
        run: docker login -u masnagam -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image
        run: docker push masnagam/mirakc:${{ matrix.arch }}
  build-multiarch-image:
    runs-on: ubuntu-latest
    needs: build-images
    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - uses: actions/checkout@v1
      - name: Login to DockerHub
        run: docker login -u masnagam -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push a multiarch image to DockerHub
        run: >-
          docker buildx build
          -f Dockerfile.multiarch
          -t masnagam/mirakc
          --platform 'linux/amd64,linux/arm/v5,linux/arm/v7,linux/arm64/v8'
          --push
          .
